app/control_lists/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import (
    TextAreaField,
    StringField,
    SubmitField,
)
from wtforms.validators import InputRequired


class SendMailToAdmin(FlaskForm):
    title = StringField('Title', validators=[InputRequired()])
    message = TextAreaField("Message", validators=[InputRequired()])
    submit = SubmitField('Send mail')


class Rename(FlaskForm):
    title = StringField('Title', validators=[InputRequired()])
    submit = SubmitField('Rename')

app/control_lists/__init__.py
from .views import control_lists_bp

app/control_lists/views.py
from flask import request, flash, redirect, url_for, Blueprint, abort, jsonify, make_response, current_app
from flask_login import current_user, login_required
from functools import wraps

import sqlalchemy.exc
from werkzeug.exceptions import BadRequest, NotFound, Forbidden


from app.main.views.utils import render_template_with_nav_info
from app.models import ControlLists, AllowedLemma, WordToken, User, PublicationStatus, CorpusCustomDictionary
from app import db, email
from ..utils import PyrrhaError
from ..utils.forms import strip_or_none
from ..utils.tsv import StringDictReader
from ..utils.response import format_api_like_reply
from .forms import SendMailToAdmin, Rename

AUTOCOMPLETE_LIMIT = 20


# Create the current blueprint
control_lists_bp = Blueprint('control_lists_bp', __name__)


def cl_editable(control_list_param: str):
    """ Rewrites a function by checking that the use have the rights to edit the CL. Passes
    the control list as an object in kwargs

    :param control_list_param: Name of the control list param
    :return: Wrapped function
    """

    def wrapper(func):
        @wraps(func)
        def decorated_view(*args, **kwargs):
            control_list, is_owner = ControlLists.get_linked_or_404(
                control_list_id=kwargs[control_list_param],
                user=current_user
            )
            can_edit = is_owner or current_user.is_admin()
            if not can_edit:
                flash("You are not an owner of the list.", category="error")
                return redirect(url_for(".get", control_list_id=kwargs[control_list_param]))
            return func(*args, control_list=control_list, **kwargs)
        return decorated_view
    return wrapper


@control_lists_bp.route('/controls', methods=["GET"])
@login_required
def home():
    return "Not written", 404


@control_lists_bp.route('/controls/<int:control_list_id>', methods=["GET"])
@login_required
def get(control_list_id):
    control_list, is_owner = ControlLists.get_linked_or_404(control_list_id=control_list_id, user=current_user)
    return render_template_with_nav_info(
        "control_lists/control_list.html",
        control_list=control_list,
        is_owner=is_owner,
        can_edit=is_owner or current_user.is_admin(),
    )


@control_lists_bp.route('/controls/<int:control_list_id>/read/lemma', methods=["GET", "UPDATE", "DELETE"])
@login_required
def lemma_list(control_list_id):
    control_list, is_owner = ControlLists.get_linked_or_404(control_list_id=control_list_id, user=current_user)
    can_edit = is_owner or current_user.is_admin()
    if request.method == "DELETE" and can_edit:
        value = request.args.get("id")
        lemma = AllowedLemma.query.get_or_404(value)
        try:
            AllowedLemma.query.filter(
                AllowedLemma.id == lemma.id,
                AllowedLemma.control_list == control_list_id
            ).delete()
            db.session.commit()
            return "", 200
        except Exception as E:
            db.session.rollback()
            return abort(403)
    elif request.method == "UPDATE" and request.mimetype == "application/json" and can_edit:
        form = request.get_json().get("lemmas", None)
        if not form:
            return abort(400, jsonify({"message": "No lemma were passed."}))
        lemmas = list(set(form.split()))
        try:
            AllowedLemma.add_batch(lemmas, control_list.id, _commit=True)
            return jsonify({"message": "Data saved"})
        except ValueError as E:
            db.session.rollback()
            return make_response(jsonify({"message": str(E)}), 400)
        except sqlalchemy.exc.StatementError as E:
            db.session.rollback()
            error = str(E.orig)
            if error.startswith("UNIQUE constraint failed"):
                return make_response(jsonify({"message": "One of the lemma you submitted already exist. "
                                                         "Remove this lemma and resubmit."}), 400)
            return make_response(jsonify({"message": "Database error. Contact the administrator."}), 400)
        except Exception as E:
            db.session.rollback()
            return make_response(jsonify({"message": "Unknown Error"}), 400)
    elif request.method == "GET":
        kwargs = {}
        page = request.args.get("page", "1")
        page = (page.isnumeric()) and int(page) or 1

        limit = request.args.get("limit", "1000")
        limit = (limit.isnumeric()) and int(limit) or 1
        kw = strip_or_none(request.args.get("kw", ""))
        template = "control_lists/read_lemma.html"
        allowed_values = control_list.get_allowed_values(
            allowed_type="lemma",
            kw=kw
        ).paginate(page=page, per_page=limit)
        kwargs["kw"] = kw

        return render_template_with_nav_info(
            template=template,
            control_list=control_list,
            is_owner=is_owner,
            allowed_type="lemma",
            can_edit=is_owner or current_user.is_admin(),
            allowed_values=allowed_values,
            readable=False,
            **kwargs
        )
    return abort(405)


@control_lists_bp.route('/controls/<int:control_list_id>/read/<allowed_type>', methods=["GET"])
@login_required
def read_allowed_values(control_list_id, allowed_type):
    if allowed_type not in ["POS", "morph"]:
        flash("The category you selected is wrong petit coquin !", category="error")
        return redirect(url_for(".get", control_list_id=control_list_id))

    control_list, is_owner = ControlLists.get_linked_or_404(control_list_id=control_list_id, user=current_user)
    kwargs = {}

    template = "control_lists/read.html"
    allowed_values = control_list.get_allowed_values(allowed_type=allowed_type).all()

    return render_template_with_nav_info(
        template=template,
        control_list=control_list,
        is_owner=is_owner,
        can_edit=is_owner or current_user.is_admin(),
        allowed_type=allowed_type,
        allowed_values=allowed_values,
        readable=allowed_type == "morph",
        **kwargs
    )


@control_lists_bp.route('/controls/<int:cl_id>/edit/<allowed_type>', methods=["GET", "POST"])
@login_required
@cl_editable("cl_id")
def edit(cl_id, allowed_type, control_list):
    """ Find allowed values and allow their edition

    :param cl_id: Id of the Control List
    :param allowed_type: Type of allowed value (lemma, morph, POS)
    """
    if allowed_type not in ["lemma", "POS", "morph"]:
        raise NotFound("Unknown type of resource.")

    # In case of Post
    if request.method == "POST":
        allowed_values = request.form.get("allowed_values")
        if allowed_type == "lemma":
            allowed_values = [
                x.replace('\r', '')
                for x in allowed_values.split("\n")
                if len(x.replace('\r', '').strip()) > 0
            ]
        elif allowed_type == "POS":
            allowed_values = [
                x.replace('\r', '')
                for x in allowed_values.split(",")
                if len(x.replace('\r', '').strip()) > 0
            ]
        else:
            allowed_values = list(StringDictReader(allowed_values))
        try:
            control_list.update_allowed_values(allowed_type, allowed_values)
            flash("Control List Updated", category="success")
        except PyrrhaError as exception:
            flash("A Pyrrha error occurred: {}".format(exception), category="error")
        except:
            flash("An unknown error occurred", category="error")

    values = control_list.get_allowed_values(allowed_type=allowed_type, order_by="id")
    if allowed_type == "lemma":
        format_message = "This should be formatted as a list of lemma separated by new line"
        values = "\n".join([d.label for d in values])
    elif allowed_type == "POS":
        format_message = "This should be formatted as a list of POS separated by comma and no space"
        values = ",".join([d.label for d in values])
    else:
        format_message = "The TSV should at least have the header : label and could have a readable column for human"
        values = "\n".join(
            ["label\treadable"] + ["{}\t{}".format(d.label, d.readable) for d in values]
        )
    return render_template_with_nav_info(
        "control_lists/edit.html",
        format_message=format_message,
        values=values,
        allowed_type=allowed_type,
        control_list=control_list
    )


@control_lists_bp.route('/controls/<int:control_list_id>/api/<allowed_type>')
@login_required
def search_api(control_list_id, allowed_type):
    """ Find allowed values

    :param control_list_id: Id of the Control List
    :param allowed_type: Type of allowed value (lemma, morph, POS)
    """
    return jsonify(
        [
            format_api_like_reply(result, allowed_type)
            for result in WordToken.get_like(
                filter_id=control_list_id,
                form=request.args.get("form"),
                group_by=True,
                type_like=allowed_type,
                allowed_list=True
            ).limit(AUTOCOMPLETE_LIMIT)
            if result is not None
        ]
    )


@control_lists_bp.route('/controls/<int:control_list_id>/contact', methods=["GET", "POST"])
@login_required
def contact(control_list_id):
    """ This routes allows user to send email to list administrators
    """
    control_list, is_owner = ControlLists.get_linked_or_404(control_list_id=control_list_id, user=current_user)

    form = SendMailToAdmin(prefix="mail")

    if request.method == "POST" and form.validate_on_submit():
        control_list_link = url_for('control_lists_bp.get', control_list_id=control_list_id, _external=True)
        email.send_email_async(
            app=current_app._get_current_object(),
            bcc=[u[3] for u in control_list.owners] + [current_user.email],
            recipient=[],

app/templates/control_lists/contact.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2>
                <i class="fa fa-envelope mr-2"></i>{{ _('Contact control lists administrators') }}
            </h2>
            <p class="form-text">{{ _('This page is built so that you can contact administrators of a control list to propose
            new lemma, POS or morphologies accepted values. We have preferred to use email so that discussion could be rich
            when needed.') }}</p>
        </div>
        <div class="row ">
            <div class="ml-3 col-sm-6">
                {{ f.render_form(form, action=url_for('.contact', control_list_id=control_list.id)) }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/control_lists/control_list.html
{% extends 'layouts/base.html' %}
{% import 'macros/utils.html' as utils %}


{% block page_title %}Control List {{control_list.name}}{% endblock %}

{% block content %}
    <div>
        <h1>{{control_list.name}}</h1>
        <h2>{{ _('Description') }}</h2>
        <p>{{control_list.description or ""}}</p>

        <h2>{{ _('Bibliography') }}</h2>
        <p>{{(control_list.bibliography or "")| markdown}}</p>


        {%- if is_owner %}
            <h2>{{ _('Information') }}</h2>
            <p class="text-info">{{ _('You are an owner of this control list') }}</p>
            <p>{{ utils.status_badge(control_list.str_public) }}</p>
            <dl>
                <dt>{{ _('Owners') }}</dt>
                {% for owner_first_name, owner_last_name, owner_id, owner_mail in control_list.owners %}
                    <dd>{{ owner_last_name }}, {{ owner_first_name }} [{{ owner_mail }}]</dd>
                {% endfor %}
            </dl>
        {% endif -%}
        {%- if can_edit %}
            <h2>{{ _('Rewrite') }}</h2>
            <p class="text-muted">{{ _('The following pages are made to completely rewrite control lists. Use with caution !') }}</p>
            <p>
                <a class="btn btn-warning settings-lemma" href="{{url_for('.edit', cl_id=control_list.id, allowed_type='lemma')}}">{{ _('Rewrite Lemma List') }}</a>
                <a class="btn btn-warning settings-POS" href="{{url_for('.edit', cl_id=control_list.id, allowed_type='POS')}}">{{ _('Rewrite POS List') }}</a>
                <a class="btn btn-warning settings-morph" href="{{url_for('.edit', cl_id=control_list.id, allowed_type='morph')}}">{{ _('Rewrite Morphology List') }}</a>
            </p>
        {% endif -%}
        {% if current_user.is_admin() and control_list.str_public != 'public' %}
            <h2>{{ _('DANGER ZONE') }}</h2>
            <p><a class="btn btn-danger" href="{{url_for('.go_public', control_list_id=control_list.id)}}">{{ _('Make public') }}</a></p>
        {%  endif %}
    </div>
{% endblock %}

app/templates/control_lists/edit.html
{% extends 'layouts/base.html' %}
{% import 'macros/tokens_macros.html' as tokens_macros %}
{% import 'macros/header_macros.html' as header_macros %}
{% import 'macros/upload_text.html' as upload_text %}

{% block page_title %}Control List {{control_list.name}}{% endblock %}

{% block content %}

<h2>Edit allowed {{allowed_type}}</h2>
<form method="post" action="{{url_for('control_lists_bp.edit', cl_id=control_list.id, allowed_type=allowed_type)}}">
    <div class="form-group">
        <label for="allowed_values">Allowed {{allowed_type}}</label>
        <small id="allowed_values_help" class="form-text text-muted">{{format_message}}</small>
        {{ upload_text.upload_text("allowed_values") }}
        <textarea aria-describedby="allowed_values_help" class="form-control" id="allowed_values" name="allowed_values">{{values}}</textarea>
    </div>
    <button type="submit" id="submit" class="btn btn-primary">{{ _('Submit') }}</button>
</form>
{% endblock %}

app/templates/control_lists/information_edit.html
{% extends 'layouts/base.html' %}

{% block page_title %}Control List {{control_list.name}}{% endblock %}

{% block content %}

<h2>Edit information about {{control_list.name}}</h2>
<form method="post" action="{{url_for('control_lists_bp.information_edit', control_list_id=control_list.id)}}">
    <div class="form-group">
        <label for="cl_description">{{ _('Description') }}</label>
        <small id="cl_description_help" class="form-text text-muted">{{ _('Description of the control list') }}</small>
        <textarea aria-describedby="cl_description_help"
                  class="form-control" id="cl_description" name="cl_description">{{control_list.description  or ""}}</textarea>
    </div>
    <div class="form-group">
        <label for="cl_language">{{ _('Language') }}</label>
        <small id="cl_language_help" class="form-text text-muted">{{ _('Language, using') }}
            <a href="https://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-2">ISO 632-2</a></small>
        <input aria-describedby="cl_language_help"
                  class="form-control" id="cl_language" name="cl_language" value="{{control_list.language  or ""}}"/>
    </div>
    <div class="form-group">
        <label for="cl_bibliography">{{ _('Bibliography') }}</label>
        <small id="cl_bibliography_help" class="form-text text-muted">{{ _('Bibliography of the control list') }}</small>
        <textarea aria-describedby="cl_bibliography_help"
                  class="form-control" id="cl_bibliography" name="cl_bibliography">{{control_list.bibliography or ""}}</textarea>
    </div>
    <div class="form-group">
        <label for="cl_notes">{{ _('Guidelines') }}</label>
        <small id="cl_notes_help" class="form-text text-muted">{{ _('All the relevant information that might be of help
        about how to tag using your control list. Can link to external data and use') }} <a href="https://daringfireball.net/projects/markdown/syntax#list">markdown</a></small>
        <textarea aria-describedby="cl_notes_help"
                  class="form-control" id="cl_notes" name="cl_notes">{{control_list.notes or ""}}</textarea>
    </div>
    <button type="submit" id="submit" class="btn btn-primary">{{ _('Submit') }}</button>
</form>
{% endblock %}

app/templates/control_lists/information_read.html
{% extends 'layouts/base.html' %}

{% block page_title %}Control List {{control_list.name}} : Guidelines{% endblock %}

{% block content %}

<h3>{{ _('Guidelines') }}</h3>
{% if control_list.notes %}
  {{ control_list.notes | markdown }}
{% else %}
  {{ "*No guidelines available at this moment.*" | markdown}}
{% endif %}

{% if control_list.bibliography %}
<h3>{{ _('Bibliography') }}</h3>
<p>{{control_list.bibliography | markdown}}</p>
{% endif %}

{% endblock %}

app/templates/control_lists/macros.html
{% import 'macros/utils.html' as utils %}

{%- macro nav_control_list(control_list, admin=True) %}
    <header>
        <a id="overview_{{control_list.id}}" href="{{url_for("control_lists_bp.get", control_list_id=control_list.id)}}">{{control_list.name}}</a>
    </header>
    <div class="text-right">{{ utils.status_badge(control_list.str_public) }}</div>
    <ul class="nav flex-column">
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.information_read", control_list_id=control_list.id)}}"><i class="fa fa-book"></i> {{ _('Guidelines') }}</a></li>
    </ul>
    {{ _('Manage Lists') }}
    <ul class="nav flex-column">
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.read_allowed_values", control_list_id=control_list.id, allowed_type='lemma')}}">{{ _('Lemma') }}</a></li>
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.read_allowed_values", control_list_id=control_list.id, allowed_type='POS')}}">{{ _('POS') }}</a></li>
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.read_allowed_values", control_list_id=control_list.id, allowed_type='morph')}}">{{ _('Morphologies') }}</a></li>
    </ul>
    {{ _('Others') }}
    <ul class="nav flex-column">
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.contact", control_list_id=control_list.id)}}"><i class="fa fa-envelope"></i> {{ _('Propose changes') }}</a></li>
      {%  if control_list.can_edit() and not current_user.is_admin() %}
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.propose_as_public", control_list_id=control_list.id)}}"><i class="fa fa-share-alt"></i> {{ _('Make public') }}</a></li>
      {% endif %}
      {%  if control_list.can_edit() or current_user.is_admin() %}
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.rename", control_list_id=control_list.id)}}"><i class="fa fa-edit"></i> {{ _('Rename') }}</a></li>
      {% endif %}
      {%  if control_list.can_edit() or current_user.is_admin() %}
      <li class="nav-item"><a class="nav-link" href="{{url_for("control_lists_bp.information_edit", control_list_id=control_list.id)}}"><i class="fa fa-edit"></i> {{ _('Edit informations') }}</a></li>
      {% endif %}
    </ul>
{% endmacro -%}

app/templates/control_lists/propose_as_public.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2>
                <i class="fa fa-share-alt mr-2"></i>{{ _('Propose the list as public list') }}
            </h2>
            <p class="form-text">{{ _('Through this form, you will contact the administrators to ask them for
            making this control list public. A public control list can not be made private again.') }}<br />{{ _('By making this
                list public, other users will be able to freely access this control list. They will be able
            to contact the administrators of this list to propose new allowed values such as lemma.') }}</p>
        </div>
        <div class="row ">
            <div class="ml-3 col-sm-6">
                {{ f.render_form(form, action=url_for('.propose_as_public', control_list_id=control_list.id)) }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/control_lists/read.html
{% extends 'layouts/base.html' %}

{% block page_title %}Control List {{control_list.name}}{% endblock %}

{% block content %}
<h1>{{control_list.name}}</h1>
<h2>{{ _('Allowed values for') }} {{allowed_type}}</h2>
{% if allowed_values %}
<table class="table table-sm small">
    <thead><tr><th>Label</th>{% if readable %}<th>{{ _('Readable') }}</th>{% endif %}</tr></thead>
    <tbody>
        {%  if readable %}
            {%- for token in allowed_values %}
            <tr class="allowed">
                <td class="label">{{token.label}}</td>
                <td class="readable">{{token.readable}}</td>
            </tr>
            {% endfor -%}
        {% else %}
            {%- for token in allowed_values %}
            <tr class="allowed">
                <td class="label">{{token.label}}</td>
            </tr>
            {% endfor -%}
        {% endif %}
    </tbody>
</table>
{% else %}<p>{{ _('No allowed value in this category') }}</p>
{% endif %}
{% endblock %}

app/templates/control_lists/read_lemma.html
{% extends 'layouts/base.html' %}
{% import 'macros/nav_macros.html' as nav %}

{% block page_title %}Control List {{control_list.name}}{% endblock %}

{% block content %}
<h1>{{control_list.name}}</h1>
<h2>{{ _('Control List for Lemmas') }}</h2>

{% if can_edit %}
<div class="form" style="padding-bottom: 10px;">
  <form id="lemma_update" class="form" style="margin-top:1em;" method="POST" action="{{url_for('control_lists_bp.lemma_list', control_list_id=control_list.id)}}">
    <div class="form-group row">
      <div class="col-md-3">
        <button class="btn btn-outline-info" id="show_lemma"><i class="fa fa-pencil-square-o"></i> {{ _('Add new lemma') }}</button></div>
      <div class="col-md-3" style="display: none;" id="show_lemma_container">
        <textarea name="lemmas" class="form-control" placeholder="One lemma per line" aria-label="Add new lemma" id="submit_lemma_textarea"></textarea>
        <button type="submit" class="btn btn-primary" style="margin-top: 1em;" id="submit_lemma">{{ _('Save the new lemmas') }}</button>
        <div>
          <span id="lemma_saving" class="hidden-default lemma_badge text-secondary border-secondary border rounded badge"><i class="fa fa-spinner fa-spin"></i> {{ _('Saving') }}</span>
          <span id="lemma_saved" class="hidden-default lemma_badge text-success border-success border rounded badge"><i class="fa fa-check-circle-o"></i> {{ _('Saved') }}</span>
          <span id="lemma_error" class="hidden-default lemma_badge text-danger border-danger border rounded badge"><i class="fa fa-check-circle-o"></i> {{ _('Error:') }}' <span class="message"></span> </span>
        </div>
      </div>
    </div>
  </form>
</div>
{% endif %}

<div class="row">
  <div class="col-sm-12">
    <h3>{{ _('Results') }}</h3>
    <small class="text-muted">There is {{allowed_values.total}} lemma{% if kw %} for this query{% endif %}.</small>
    <form method="GET" class="col-md-3">
        <div class="input-group input-group-sm">
          <div class="input-group-prepend">
            <button type="submit" class="btn btn-outline-primary" id="searchLemma">{{ _('Search for') }}</button>
          </div>
          <input type="text" name="kw" class="form-control-sm form-control" value="{{kw}}" placeholder="Search a lemma" aria-label="Search Lemma" aria-describedby="searchLemma">
          <div class="input-group-append">
            <button type="button" class="btn btn-outline-info" id="searchHelp"><i class="fa fa-plus-circle"></i> {{ _('Show help') }} </button>
          </div>
        </div>
        <div class="text-muted small" id="searchHelpBox" style="display: none;">
          {{ _('Options :') }}
          <ul>
            <li>{{ _('* can be used to match partial words, eg.') }} <b>ADV*</b></li>
            <li>{{ _('! can be used to negate a match, eg.') }} <b>!PRE</b></li>
            <li>{{ _('| can be used to perform an OR operation, eg.) }} <b>s*t | s*s</b></li>
            <li>{{ _('To search forms which do not contain') }} 'e': <b>! *e*</b></li>
          </ul>
        </div>
    </form>
    <ul id="lemma-list">
    {%- if can_edit %}
    {%- for token in allowed_values.items %}
        <li><a class="rm-lem" href="{{url_for('control_lists_bp.lemma_list', control_list_id=control_list.id, id=token.id)}}"><i aria-label="Remove" class="fa fa-trash-o"></i></a>&nbsp;{{token.label}}</li>
    {% endfor -%}
    {% else %}
    {%- for token in allowed_values.items %}
        <li>{{token.label}}</li>
    {% endfor -%}
    {% endif -%}
    </ul>
    {{ nav.render_pagination(pagination=allowed_values, endpoint='control_lists_bp.lemma_list', control_list_id=control_list.id, kw=kw)}}
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
      $("#searchHelp").on("click", function(event) {
          event.preventDefault();
          $("#searchHelpBox").toggle();
      });

      {%- if can_edit %}
      var use_badge = function(badges, show, message) {
          /** Display a badge of the Lemma form
           *
           * badges : jQuery selector of badges
           * show : suffix of the badge id (what's after #badge_
           * message : Error message to show [Optional]
           */
          if (message === undefined) { message = "Erreur inconnue"; }
          // Hide all the badges !
          badges.hide();
          // Select the one badge to deal with
          var single = $("#lemma_"+show);
          // If there is an error message
          if (show === "error") { single.find(".message").text(message); }
          // Show it
          single.show();
      };
      $("#show_lemma").on("click", function(event) {
          event.preventDefault();
          $("#show_lemma_container").toggle();
      });
      $("#lemma_update").on("submit", function(e) {
         e.preventDefault();
         var badges = $(".lemma_badge"),
             form = $(this),
             value= $("#submit_lemma_textarea").val(),
             error = false;

         use_badge(badges, "saving");

         if (value.trim().length == 0) {
             use_badge(badges, "error", "Form input is empty.");
             error = true;
         }
         if (error === false){
             $.ajax({
                 url:form.attr("action"),
                 data: JSON.stringify({"lemmas": value}),
                 method:"UPDATE",
                 contentType: 'application/json'
             }).done(function() { use_badge(badges, "saved"); })
               .fail(function(data) { use_badge(badges, "error", data.responseJSON.message); });
         }

      });
      $(".rm-lem").on("click", function(event) {
          event.preventDefault();
          var that = $(this),
              parent = that.parent()
          $.ajax({
            url:that.attr("href"),
            method:"DELETE"
          })
              .done(function() { parent.remove(); })
              .fail(function() { alert("Error while removing the value"); });
      });
      {% endif -%}
  });
</script>
{% endblock %}

app/templates/control_lists/rename.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2>
                <i class="fa fa-edit mr-2"></i>{{ _('Rename the control list') }}
            </h2>
        </div>
        <div class="row ">
            <div class="ml-3 col-sm-6">
                {{ f.render_form(form, action=url_for('.rename', control_list_id=control_list.id)) }}
            </div>
        </div>
    </div>
{% endblock %}